# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Post.destroy_all
Doctor.destroy_all

puts "creating doctors"

Doctor.create(first_name: "Dean", middle_name: "M", last_name: "Ishiki", title: "Psychiatrist, MD", img_url: "https://asset3.betterdoctor.com/assets/general_doctor_male.png", gender: "male", location_slug: "wa-seattle", office_name: "First Hill Therapists", accept_new_patients: true, city: "Seattle", lat: 47.60631, lon: -122.32177, state: "Washington", street: "515 Minor Ave", street2: "Ste 230", zip: "98104", phone: "206-622-9496", bio: "Dr. Dean Ishiki, MD treats patients in Seattle, Washington and specializes in addiction psychiatry, child & adolescent psychiatry, clinical neurophysiology, cognitive & behavioral psychology, counseling psychology, psychiatry, psychology, psychiatry & neurology behavioral neurology & neuropsychiatry, psychiatry & neurology diagnostic neuroimaging, psychiatry & neurology forensic psychiatry, psychiatry & neurology hospice and palliative medicine, psychiatry & neurology psychosomatic medicine, and psychiatry & neurology pain medicine. Dr. Ishiki is licensed to treat patients in Washington. Dr. Ishiki has been found during an automated background check to be clear of any malpractice history and holds one or more active medical licenses.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "David", middle_name: "L", last_name: "Dunner", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "wa-mercer-island", office_name: "Center For Anxiety Depression", accept_new_patients: true, city: "Mercer Island", lat: 47.58865, lon: -122.23853, state: "Washington", street: "7525 SE 24th St", street2: "Ste 400", zip: "98040", phone: "2062300330", bio: "Dr. David Dunner, MD sees patients in Mercer island, Washington, specializing in psychiatry. Dr. Dunner is licensed to see patients in Washington. In addition to having active medical licenses, Dr. Dunner has been found to hold one or more active medical licenses, and successfully passed a malpractice history screening.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "Dilip", middle_name: "A", last_name: "Shah", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "nj-clifton", office_name: "Anxiety Depression Associates", accept_new_patients: true, city: "Clifton", lat: 40.869966, lon: -74.154793, state: "New Jersey", street: "721 Clifton Ave", street2: "Ste 2C", zip: "07013", phone: "9734718888", bio: "Dr. Dilip Shah, MD, specialist in psychiatry, currently sees patients in Clifton, New Jersey and Newark, New Jersey.\n\nDr. Shah is licensed to practice medicine at New Jersey.\n\nIn addition to having active medical licenses, Dr. Shah has passed an automated background check which looked at elements including medical license status and malpractice screening (no history found).", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "Shahidul", middle_name: "", last_name: "Islam", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "tn-nashville", office_name: "Anxiety Depression Dsordr Clin", accept_new_patients: true, city: "Nashville", lat: 36.15707, lon: -86.80539, state: "Tennessee", street: "2014 Charlotte Ave", street2: "", zip: "37203", phone: "6153291755", bio: "Dr. Shahidul Islam, MD is one of the country's top rated doctors. His specialties include psychiatry and he currently practices medicine at Nashville, Tennessee and Shreveport, Louisiana.\n\nDr. Islam is licensed to treat patients in Tennessee.\n\nBased on his experience, credentials and network, Dr. Islam has been found to be among the top 20% of all doctors in the United States.\n\nIn addition, Dr. Islam has been found during an automated background check to be clear of any malpractice history and holds one or more active medical licenses.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "John", middle_name: "William", last_name: "Fenton", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "ca-san-leandro", office_name: "Psychiatrist Unit B", accept_new_patients: true, city: "San Leandro", lat: 37.71072, lon: -122.12023, state: "California", street: "2060 Fairmont Dr", street2: "", zip: "94578", phone: "5103461446", bio: "Dr. John Fenton, MD sees patients in San leandro, California and specializes in ophthalmology and psychiatry.\n\nDr. Fenton is licensed to practice optometry and medicine at California.\n\nIn addition to having active medical licenses, Dr. Fenton has passed an automated background check which looked at elements including medical license status and malpractice screening (no history found).", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "Pavan", middle_name: "", last_name: "Pancholy", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "fl-tampa", office_name: "Mhc Inc Psychiatrist", accept_new_patients: true, city: "Tampa", lat: 27.99106, lon: -82.48334, state: "Florida", street: "2313 W Violet St", street2: "", zip: "33603", phone: "8136734622", bio: "Dr. Pavan Pancholy, MD--specialist in psychiatry--currently treats patients in Tampa, Florida.\n\nDr. Pancholy is licensed to practice medicine at Louisiana and Florida.\n\nDr. Pancholy has been found to hold one or more active medical licenses, and successfully passed a malpractice history screening.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "Richard", middle_name: "Clay", last_name: "Johansson", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "nh-hampstead", office_name: "Psychiatrist Hampstead", accept_new_patients: true, city: "Hampstead", lat: 42.871663, lon: -71.154242, state: "New Hampshire", street: "218 East Rd", street2: "", zip: "03841", phone: "6033295311", bio: "Dr. Richard Johansson, MD, specialist in child & adolescent psychiatry and psychiatry, currently practices medicine at Hampstead, New Hampshire." "Dr. Johansson is licensed to practice medicine at New Hampshire.\n\nIn addition to having active medical licenses, Dr. Johansson has been found during an automated background check to be clear of any malpractice history and holds one or more active medical licenses.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "Patricia", middle_name: "E", last_name: "Shea", title: "PSYD", img_url: "https://imgur.com/a/2ETwkzN", gender: "female", location_slug: "nh-hampstead", office_name: "Psychiatrist Hampstead", accept_new_patients: true, city: "Hampstead", lat: 42.871663, lon: -71.154242, state: "New Hampshire", street: "218 East Rd", street2: "", zip: "03841", phone: "6033295311", bio: "Dr. Patricia Shea, PSYD sees patients in Hampstead, New Hampshire, specializing in psychology.\n\nDr. Shea is licensed to practice medicine at New Hampshire.\n\nIn addition to having active medical licenses, Dr. Shea has been found during an automated background check to be clear of any malpractice history and holds one or more active medical licenses.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of mental disorders.")
Doctor.create(first_name: "Rafael", middle_name: "", last_name: "Tatay", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "ne-lincoln", office_name: "PLAZA WEST PSYCHIATRISTS", accept_new_patients: true, city: "Lincoln", lat: 40.788242, lon: -96.699029, state: "Nebraska", street: "2222 S 16th St", street2: "Ste 330", zip: "68502", phone: "4024741511", bio: "Dr. Rafael Tatay, MD practices medicine at Lincoln, Nebraska, specializing in addiction psychiatry, child & adolescent psychiatry, clinical neurophysiology, psychiatry, psychiatry & neurology behavioral neurology & neuropsychiatry, psychiatry & neurology diagnostic neuroimaging, psychiatry & neurology forensic psychiatry, psychiatry & neurology hospice and palliative medicine, psychiatry & neurology psychosomatic medicine, and psychiatry & neurology pain medicine.\n\nDr. Tatay is licensed to see patients in Nebraska.\n\nIn addition to having active medical licenses, Dr. Tatay has successfully passed a background check including a medical license verification (active) and screening for malpractice history (none found).", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
Doctor.create(first_name: "Leonard", middle_name: "", last_name: "Diamond", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "ct-new-milford", office_name: "Associated Psychiatrists", accept_new_patients: true, city: "New Milford", lat: 41.57445, lon: -73.40988, state: "Connecticut", street: "29 S Main St", street2: "", zip: "06776", phone: "8603541111", bio: "Dr. Leonard Diamond, MD, specialist in prescribing (medical) psychology and psychiatry, currently treats patients in New york, New York and New milford, Connecticut.\n\nDr. Diamond graduated from Suny Downstate Medicine Ctr and is licensed to practice medicine at Connecticut.\n\nDr. Diamond has passed an automated background check which looked at elements including medical license status and malpractice screening (no history found).", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
Doctor.create(first_name: "Jane", middle_name: "", last_name: "Kou", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "female", location_slug: "ny-syracuse", office_name: "DR. JANE KOU, PSYCHIATRIST, LLC", accept_new_patients: true, city: "Syracuse", lat: 43.042477, lon: -76.15156, state: "New York", street: "610 S Salina St", street2: "", zip: "13202", phone: "3154217479", bio: "Dr. Jane Kou is a psychiatrist in Syracuse, New York and is affiliated with St. Joseph's Hospital Health Center. She received her medical degree from Dow Medical College and has been in practice for 35 years. She is one of 15 doctors at St. Joseph's Hospital Health Center who specialize in Psychiatry.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
Doctor.create(first_name: "William", middle_name: "Stuart", last_name: "Hudson", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "male", location_slug: "ga-columbus", office_name: "St Francis Psychiatristllc", accept_new_patients: true, city: "Columbus", lat: 32.482735, lon: -84.968315, state: "Georgia", street: "2000 16th Ave", street2: "", zip: "31901", phone: "7063203770", bio: "Dr. William Hudson, MD--specialist in psychiatry--currently practices medicine at Columbus, Georgia, Atlanta, Georgia, Asheville, North Carolina, Alpharetta, Georgia, Cumming, Georgia, and Arden, North Carolina.\n\n\n\nIn addition to having active medical licenses, Dr. Hudson has been found during an automated background check to be clear of any malpractice history and holds one or more active medical licenses.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
Doctor.create(first_name: "Dinar", middle_name: "", last_name: "Sajan", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "female", location_slug: "fl-clearwater", office_name: "Health & Psychiatrist Consultants LLC", accept_new_patients: true, city: "Clearwater", lat: 28.019375, lon: -82.728409, state: "Florida", street: "2655 State Road 580", street2: "Ste 202", zip: "33761", phone: "7277336111", bio: "Dr. Dinar Sajan, MD--specialist in psychiatry--currently sees patients in Clearwater, Florida and Dunedin, Florida.\n\nDr. Sajan is licensed to treat patients in Florida.\n\nIn addition to having active medical licenses, Dr. Sajan has successfully passed a background check including a medical license verification (active) and screening for malpractice history (none found).", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
Doctor.create(first_name: "Sandra", middle_name: "J", last_name: "Krussell", title: "Psychiatrist, MD", img_url: "https://imgur.com/a/2ETwkzN", gender: "female", location_slug: "or-portland", office_name: "Sandra J. Krussel, Do, Psychiatrist, LLC", accept_new_patients: true, city:"Portland", lat: 45.52672, lon: -122.69824, state: "Oregon", street: "530 NW 23rd Ave", street2: "Ste 117", zip: "97210", phone:"9713026451", bio: "Dr. Sandra Krussel, DO specializes in psychiatry, and currently treats patients in Portland, Oregon.\n\nDr. Krussel is licensed to treat patients in Oregon.\n\nIn addition to having active medical licenses, Dr. Krussel has successfully passed a background check including a medical license verification (active) and screening for malpractice history (none found).", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
Doctor.create(first_name: "Casey", middle_name: "Clark", last_name: "Arney", title: "Psychiatrist, MD", img_url: "https://asset2.betterdoctor.com/images/546184524214f82e87000009-2_thumbnail.jpg", gender: "male", location_slug: "tn-nashville", office_name: "Associated Psychiatrists Of Nashville", accept_new_patients: true, city: "Nashville", lat: 36.09544, lon: -86.82306, state: "Tennessee", street: "30 Burton Hills Blvd", street2: "Ste 375", zip: "37215", phone: "6153274877", bio: "Since beginning private practice in 1992, Dr Arney has enjoyed the work of office- based psychiatry. He particularly appreciates the effectiveness of combining different modes of treatment – psychotherapy, medication, and ancillary treatments- to help bring about needed change in his patient’s lives. In practice he addresses a range of issues including depression, anxiety, bipolar disorder, attention deficit disorder, grief, and difficulties adjusting to life changes. Dr Arney believes that a healthy mind requires attention to physical, emotional, spiritual, and relational health.\n\nA wide range of professional experiences informs Dr Arney’s work including forensic psychiatry, psychoanalysis, cognitive behavioral therapy, and experiential therapy. He attended medical school at University of Louisville School of Medicine, internship at Loyola University Medical Center, and residency at Vanderbilt University Medical Center. He remains on clinical faculty at Vanderbilt as Assistant Clinical Professor and enjoys supervising and teaching residents. He also maintains a weekly clinic at Vanderbilt University where he treats students. Dr Arney is certified in psychiatry by the American Board of Psychiatry and Neurology.", practice: "Psychiatry", description: "Specializes in the diagnosis and treatment of children's mental disorders.")
puts "done creating doctors"

puts "creating users"
User.create(name: "Test", email: "Test@test.com", password_digest: "test", profile_img: "test" )
puts "done creating users"

puts "creating posts"
Post.create(title: "First Post", body: "Hello there", user: User.all.sample)
puts "done creating posts"
